import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getStaticProps(){
  const res = await fetch("http://localhost:3000/api/tip")
  const tip = await res.json();

  return {
    props:{ tip },
  };
}



export default function Home({ tip }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Random tips
        </h1>

        <h2>{ tip.title }</h2>
        <p> { tip.description }</p>
        <p> { tip.author }</p>

        
      </main>

      <footer className={styles.footer}>
    
          Powered by Open Source
          <span className={styles.logo}>
            
          </span>

      </footer>
    </div>
  )
}
